---
title: "DS Final Project"
author: "Madeline Braun"
date: "3/5/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r}
library(tidyverse)
library(lubridate)
library(maps)
library(ggmap)
library(ggplot2)
library(RColorBrewer)
library(ggthemes)
library(maps)          # for map data
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggimage)
theme_set(theme_minimal())
```

```{r}
soil <- read_csv("soil_magnetism_data.csv")
```


```{r}
soil %>% 
  filter(avg_outlier == "average") %>% 
  mutate(traffic_class = fct_relevel(traffic_class, "low", "medium", "high")) %>%
  ggplot(aes(x = traffic_class, y = sus_avg, group = traffic_class)) +
  geom_boxplot(aes(fill = traffic_class), alpha = 0.5) +
  labs(x = "Traffic Volume Classification",
       y = "") +
  facet_wrap(~state)
```

```{r}
georgia_sites <- tibble(
  road = c("Babb Road", "Old Babb Road", "I-75 Walnut Avenue Offramp",
            "Walnut Avenue", "Mill Creek Road", "Utility Road",
            "Dalton Bypass Corporate Drive", "Dalton Bypass Caunasauga Drive",
            "George Rice Drive", "College Drive"),
  long = c(-85.040827, -85.055768, -85.002817,
            -85.000087, -85.041725, -85.051626,
            -84.940111, -84.980521, -85.003035,
            -85.002238),
  lat = c(34.736550, 34.745755, 34.761234,
          34.761107, 34.735628, 34.784041,
          34.712289, 34.697031, 34.769729,
          34.771593))

minnesota_sites <- tibble(
  road = c("Shepard Road", "Mississippi River Boulevard", 
            "Brimhall Street", "Inver Grove Trail"),
  long = c(-93.145852, -93.197918, 
           -93.165680, -93.029480),
  lat = c(44.909581, 44.914092, 
          44.932071, 44.811813))

ga_mn <- tibble(
  place = c("Dalton", "Twin Cities"),
  long = c(-84.969, -93.302),
  lat = c(34.762, 44.986))

all_sites <- tibble(
  road = c("Babb Road", "Old Babb Road", "I-75 Walnut Avenue Offramp",
            "Walnut Avenue", "Mill Creek Road", "Utility Road",
            "Dalton Bypass Corporate Drive", "Dalton Bypass Caunasauga Drive",
            "George Rice Drive", "College Drive", "Shepard Road", 
            "Mississippi River Boulevard", "Brimhall Street", "Inver Grove Trail"),
  long = c(-85.040827, -85.055768, -85.002817,
            -85.000087, -85.041725, -85.051626,
            -84.940111, -84.980521, -85.003035,
            -85.002238, -93.145852, -93.197918, 
            -93.165680, -93.029480),
  lat = c(34.736550, 34.745755, 34.761234,
          34.761107, 34.735628, 34.784041,
          34.712289, 34.697031, 34.769729,
          34.771593, 44.909581, 44.914092, 
          44.932071, 44.811813)
)
```

```{r}
soil_coord <- left_join(
  soil,
  all_sites
)
```

```{r}
soil_coord <- soil_coord %>% 
  mutate(traffic_class = fct_relevel(traffic_class, "low", "medium", "high"))
pal <- colorFactor(c("#93BA98", "#FBD061", "#E14E42"), 
                     domain = soil_coord$traffic_class)
soil_coord %>% 
  filter(state == "Minnesota", 
         distance_cm == 10) %>%
  leaflet() %>% 
    addProviderTiles("CartoDB.Voyager") %>% 
    addCircleMarkers(color = ~pal(traffic_class),
               fillOpacity = .7,
               label = ~paste(str_to_title(road),
                              ", Average Magnetic Susceptibility: ",
                              sus_avg),
               stroke = FALSE,
               radius = 10) %>% 
    addLegend(position = "bottomright",
             pal = pal, 
             values = ~traffic_class,
             title = "Traffic Volume Classification")
```


```{r}
soil_coord <- soil_coord %>% 
  mutate(traffic_class = fct_relevel(traffic_class, "low", "medium", "high"))
pal <- colorFactor(c("#93BA98", "#FBD061", "#E14E42"), 
                     domain = soil_coord$traffic_class)
soil_coord %>% 
  filter(state == "Georgia", 
         distance_cm == 10) %>%
  leaflet() %>% 
    addProviderTiles("CartoDB.Voyager") %>% 
    addCircleMarkers(color = ~pal(traffic_class),
               fillOpacity = .7,
               label = ~paste(str_to_title(road),
                              ", Average Magnetic Susceptibility: ",
                              sus_avg),
               stroke = FALSE,
               radius = 10) %>% 
    addLegend(position = "bottomright",
             pal = pal, 
             values = ~traffic_class,
             title = "Traffic Volume Classification")
```


```{r}
soil_longer <- soil %>% 
  pivot_longer(M1:M11, names_to = "site_id", values_to = "mag_sus")
```

```{r}
soil_longer %>% 
  filter(avg_outlier == "average",
         state == "Minnesota") %>% 
  mutate(traffic_class = fct_relevel(traffic_class, "low", "medium", "high")) %>%
  ggplot(aes(x = road, y = mag_sus)) +
  geom_boxplot(aes(fill = traffic_class), alpha = 0.5) +
  labs(y = "Magnetic Susceptibility (SI)",
       x = "") +
  scale_fill_manual(values = c("#93BA98", "#FBD061", "#E14E42")) +
  coord_flip()
```

```{r}
soil_longer %>% 
  filter(avg_outlier == "average",
         state == "Georgia") %>% 
  mutate(traffic_class = fct_relevel(traffic_class, "low", "medium", "high")) %>%
  ggplot(aes(x = road, y = mag_sus)) +
  geom_boxplot(aes(fill = traffic_class), alpha = 0.5) +
  labs(x = "",
       y = "Magnetic Susceptibility (SI)") +
  facet_wrap(~traffic_class, 
             scales = "free",
             nrow = 3) + 
  scale_fill_manual(values = c("#93BA98", "#FBD061", "#E14E42")) +
  coord_flip()
```


